baseurl: "https://minhua.netlify.app/"
languageCode: "en-us"
# defaultContentLanguage: "en"
defaultContentLanguage: "zh"
title: "稻说"
theme: "hugo-prose"
googleAnalytics: ""
disqusShortname: "minhua-netlify"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", ] 
# "/content/math-notes/fiber-bundles/_book/\\.md$"
footnotereturnlinkcontents: "↩"
paginate: 2

permalinks:
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: [html, rss, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    # - name: 数学笔记
    #   url: "/math-notes"
    #   weight: 2
    - name: 搜索
      url: "#"
      identifier: menu-search
      weight: 4
    - name: SSR订阅
      url: "index.xml"
  footer:
    - name: 联系方式
      url: "/404.html"
      weight: 1
    - name: 分类
      url: "/categories/"
      weight: 2
      pre: "optional"
    - name: 标签
      url: "/tags/"
      weight: 3
      pre: "optional"
    - name: 建议
      url: "#"
      weight: 4
      identifier: "menu-edit"
    - name: 回到页面顶部
      url: "#"

params:
  homePosts: 6
  mainSections: ["math","post", "work"]
  editLink: "https://github.com/mathirst/minhua.netlify.io/edit/master/content/" # 注释掉就会去掉『欢迎修订』
  # "https://github.com/yihui/hugo-prose/edit/master/exampleSite/content/"
  # 我先把『引用本文』功能关了，在 工作目录/layouts/partials/appendix 里的 {{ partial "correction.html" . }} 后面的 if author 那段，有空再修补修补
  authorDelimiter: " / "
  pageFeatures: [+sidenotes]
  description: >
    数学博士生，对认识世界有较广泛的兴趣
  footer: >
    &copy; 稻年 2022 -
  license: >
    Text and figures are licensed under [Creative Commons Attribution CC BY
    4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
    licensed under MIT. The full source is available at
    https://github.com/mathirst/mathirst.github.io.

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
